#!/bin/bash

# Update packages and install necessary tools
sudo dnf update -y

# Install Go
sudo dnf install golang -y

# Install Node.js and npm
sudo dnf install nodejs -y

# Install Nginx
sudo dnf install nginx -y

# Install pnpm globally
sudo npm install -g pnpm

# Install PM2 globally
# sudo npm install pm2@latest -g
sudo pnpm add -g pm2

# Start and enable Nginx to run on boot
sudo systemctl start nginx
sudo systemctl enable nginx

git clone https://github.com/daniil-tang/word-rally.git /home/ec2-user/word-rally

# Build server
cd /home/ec2-user/word-rally/server
go build -o word-rally-server .

# Build client
sudo export VITE_SERVER_URL="http://44.224.115.98/api"
sudo export VITE_WEBSOCKET_URL="http://44.224.115.98/ws"
cd /home/ec2-user/word-rally/client
pnpm install
pnpm run build
# pm2 start ./build/index.js --name word-rally-client

# cd /home/ec2-user/word-rally/server
# pm2 start ./word-rally-server --name word-rally-server

# Start client & server
cd /home/ec2-user/word-rally
pm2 start ecosystem.config.js 

# Configuration for reverse proxy, e.g., using Nginx for Go and SvelteKit apps (optional)
sudo bash -c 'cat <<EOF > /etc/nginx/nginx.conf
server {
    listen 80;

    # Proxy API requests to Go backend
    location /api/ {
        proxy_pass http://localhost:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;  # Required for WebSockets
        proxy_set_header Connection 'upgrade';  # Required for WebSockets
        proxy_set_header Host $host;
    }

    # Proxy frontend requests to SvelteKit SSR app
    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;  # Required for WebSockets
        proxy_set_header Connection 'upgrade';  # Required for WebSockets
        proxy_set_header Host $host;
    }

    location /ws {
        proxy_pass http://localhost:8080/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;  # Required for WebSockets
        proxy_set_header Connection 'upgrade';  # Required for WebSockets
        proxy_set_header Host $host;
    }
}
EOF'

# Restart Nginx to apply the changes
sudo systemctl restart nginx

pm2 logs